version: 2.1

orbs:
  android: circleci/android@2.1.1

jobs:
  build-test-sonar:
    docker:
      - image: cimg/android:2024.01.1
    working_directory: ~/project
    steps:
      - checkout
      
      - android/restore-build-cache
      - android/restore-gradle-cache
      
      - run:
          name: Run SonarQube analysis with Gradle
          command: |
            chmod +x ./gradlew
            ./gradlew test jacocoTestReport sonar \
              -Dsonar.projectKey=Liyakhanya_app \
              -Dsonar.organization=liyakhanya \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.sources=app/src/main/java \
              -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/test/jacocoTestReport.xml
      
      - android/save-build-cache
      - android/save-gradle-cache
      
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports

workflows:
  version: 2
  main:
    jobs:
      - build-test-sonar
